FACEBOOK_CLIENT_ID: "127239617610618"
FACEBOOK_CLIENT_SECRET: "cea7ae2de6adcb47ad0fe38abc0bf5c4"

GOOGLE_CLIENT_ID: "327919863562-t2h39picbuc8vjubqi8mkh7vi3q66a3i.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "avLPYFlepSjeZqfY8RTbIMRK"